DROP TABLE USER_INFO;
DROP SEQUENCE USER_NOSQ;

CREATE SEQUENCE USER_NOSQ NOCACHE;

CREATE TABLE USER_INFO(
	USER_NO NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(500) UNIQUE,
	USER_PW VARCHAR2(500) NOT NULL,
	USER_NAME VARCHAR2(500) NOT NULL,
	USER_GENDER VARCHAR2(2) CHECK(USER_GENDER IN('F','M') ),
	USER_BIRTHDATE VARCHAR2(500) NOT NULL,
	USER_EMAIL VARCHAR2(200) UNIQUE,
	USER_PHONE VARCHAR2(20) NOT NULL,
	USER_ZIP VARCHAR2(20) NOT NULL,
	USER_ADDR VARCHAR2(1000),
	USER_ROLE VARCHAR2(50) NOT NULL
);

DROP TABLE STADIUM;
DROP SEQUENCE STADIUM_NOSQ;

CREATE SEQUENCE STADIUM_NOSQ NOCACHE;

CREATE TABLE STADIUM(
	STADIUM_NO NUMBER PRIMARY KEY,
	STADIUM_NAME VARCHAR2(500) NOT NULL,
	STADIUM_ADDR VARCHAR2(1000) NOT NULL,
	STADIUM_CONTENT VARCHAR2(4000) NOT NULL
);

DROP TABLE REVIEW;
DROP SEQUENCE REVIEW_NO;

CREATE SEQUENCE REVIEW_NOSQ NOCACHE;

CREATE TABLE REVIEW(
	REVIEW_NO NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(500) NOT NULL,
	REVIEW_REG DATE NOT NULL,
	REVIEW_TITLE VARCHAR2(500) NOT NULL,
	REVIEW_CONTENT VARCHAR2(4000) NOT NULL,
	STADIUM_NO NUMBER NOT NULL,
	CONSTRAINT FK_USER_ID1 FOREIGN KEY(USER_ID) REFERENCES USER_INFO(USER_ID)
		ON DELETE CASCADE,
	CONSTRAINT FK_STADIUM_NO1 FOREIGN KEY(STADIUM_NO) REFERENCES STADIUM(STADIUM_NO)
		ON DELETE CASCADE
);

DROP TABLE STADIUM_PIC;
DROP SEQUENCE STADIUM_PIC_NOSQ;

CREATE SEQUENCE STADIUM_PIC_NOSQ NOCACHE;

CREATE TABLE STADIUM_PIC(
	STADIUM_NO NUMBER NOT NULL,
	PIC_NAME VARCHAR2(500) NOT NULL,
	PIC_PATH VARCHAR2(1000) NOT NULL,
	CONSTRAINT FK_STADIUM_NO2 FOREIGN KEY(STADIUM_NO) REFERENCES STADIUM(STADIUM_NO)
		ON DELETE CASCADE
);

DROP TABLE TEAM_INFO;
DROP SEQUENCE TEAM_NOSQ;

CREATE SEQUENCE TEAM_NOSQ NOCACHE;

CREATE TABLE TEAM_INFO(
	USER_NO NUMBER NOT NULL,
	USER_NAME VARCHAR2(500) NOT NULL,
	TEAM_NAME VARCHAR2(500) UNIQUE,
	TEAM_INTRO VARCHAR2(4000),
	TEAM_NO NUMBER PRIMARY KEY,
	TEAM_ADDCHK VARCHAR2(2) DEFAULT 'N' CHECK(TEAM_ADDCHK IN('Y','N') ),
	CONSTRAINT FK_USER_NO1 FOREIGN KEY(USER_NO) REFERENCES USER_INFO(USER_NO)
		ON DELETE CASCADE
);























