

CREATE SEQUENCE USER_NOSQ NOCACHE;

CREATE TABLE USER_INFO(
	USER_NO NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(500) UNIQUE,
	USER_PW VARCHAR2(500) NOT NULL,
	USER_NAME VARCHAR2(500) NOT NULL,
	USER_GENDER VARCHAR2(2) CHECK(USER_GENDER IN('F','M') ),
	USER_BIRTHDATE VARCHAR2(500) NOT NULL,
	USER_EMAIL VARCHAR2(200) UNIQUE,
	USER_PHONE VARCHAR2(20) NOT NULL,
	USER_ZIP VARCHAR2(20) NOT NULL,
	USER_ADDR VARCHAR2(1000),
	USER_ROLE VARCHAR2(50) NOT NULL,
	USER_CONCHK VARCHAR2(50)
);
CREATE SEQUENCE STADIUM_NOSQ NOCACHE;

CREATE TABLE STADIUM(
	STADIUM_NO NUMBER PRIMARY KEY,
	STADIUM_NAME VARCHAR2(500) NOT NULL,
	STADIUM_ADDR VARCHAR2(1000) NOT NULL,
	STADIUM_CONTENT VARCHAR2(4000) NOT NULL,
	STADIUM_WEBADDR VARCHAR2(1000),
	STADIUM_PHONENUM VARCHAR2(500)
);



CREATE SEQUENCE REVIEW_NOSQ NOCACHE;

CREATE TABLE REVIEW(
	REVIEW_NO NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(500) NOT NULL,
	REVIEW_REG DATE NOT NULL,
	REVIEW_TITLE VARCHAR2(500) NOT NULL,
	REVIEW_CONTENT VARCHAR2(4000) NOT NULL,
	STADIUM_NO NUMBER NOT NULL,
	CONSTRAINT FK_USER_ID1 FOREIGN KEY(USER_ID) REFERENCES USER_INFO(USER_ID)
		ON DELETE CASCADE,
	CONSTRAINT FK_STADIUM_NO1 FOREIGN KEY(STADIUM_NO) REFERENCES STADIUM(STADIUM_NO)
		ON DELETE CASCADE
);




CREATE TABLE STADIUM_PIC(
	STADIUM_NO NUMBER NOT NULL,
	PIC_NAME VARCHAR2(500) NOT NULL,
	PIC_PATH VARCHAR2(1000) NOT NULL,
	CONSTRAINT FK_STADIUM_NO2 FOREIGN KEY(STADIUM_NO) REFERENCES STADIUM(STADIUM_NO)
		ON DELETE CASCADE
);



CREATE SEQUENCE TEAM_NOSQ NOCACHE;

CREATE TABLE TEAM_INFO(
	USER_NO NUMBER NOT NULL,
	TEAM_NAME VARCHAR2(500) UNIQUE,
	TEAM_INTRO VARCHAR2(4000),
	TEAM_NO NUMBER PRIMARY KEY,
	TEAM_ADDCHK VARCHAR2(2) DEFAULT 'N' CHECK(TEAM_ADDCHK IN('Y','N') ),
	CONSTRAINT FK_USER_NO1 FOREIGN KEY(USER_NO) REFERENCES USER_INFO(USER_NO)
		ON DELETE CASCADE
);



CREATE SEQUENCE TEAM_PIC_NOSQ NOCACHE;

CREATE TABLE TEAM_PIC(
	TEAM_NO NUMBER NOT NULL,
	PIC_NAME VARCHAR2(500) NOT NULL,
	PIC_PATH VARCHAR2(1000) NOT NULL,
	CONSTRAINT FK_TEAM_NO1 FOREIGN KEY(TEAM_NO) REFERENCES TEAM_INFO(TEAM_NO)
		ON DELETE CASCADE
);



CREATE SEQUENCE TMASK_NOSQ NOCACHE;
CREATE SEQUENCE TMASK_GPNOSQ NOCACHE;
CREATE SEQUENCE TMASK_GPSQ NOCACHE;

CREATE TABLE TEAM_ASK(
	TMASK_NO NUMBER PRIMARY KEY,
	TEAM_NO NUMBER NOT NULL,
	TMASK_TYPE VARCHAR2(100) NOT NULL,
	TMASK_GPNO NUMBER NOT NULL,
	TMASK_GPSQ NUMBER NOT NULL,
	USER_ID VARCHAR2(500) NOT NULL,
	TMASK_CONTENT VARCHAR2(4000) NOT NULL,
	TMASK_REG DATE NOT NULL,
	TMASK_STATUS VARCHAR2(2) DEFAULT 'N' CHECK(TMASK_STATUS IN('Y','N') ),
	CONSTRAINT FK_TEAM_NO2 FOREIGN KEY(TEAM_NO) REFERENCES TEAM_INFO(TEAM_NO)
		ON DELETE CASCADE,
	CONSTRAINT FK_USER_ID2 FOREIGN KEY(USER_ID) REFERENCES USER_INFO(USER_ID)
		ON DELETE CASCADE
);



CREATE TABLE MERCENARY_INFO(
	USER_NO NUMBER NOT NULL,
	MERCENARY_INTRO VARCHAR2(4000),
	MERCENARY_FOOT VARCHAR2(2) DEFAULT 'R' CHECK(MERCENARY_FOOT IN('L','R','A') ),
	MERCENARY_RATE NUMBER(2,2),
	MERCENARY_POSITION VARCHAR2(100) NOT NULL,
	CONSTRAINT FK_USER_NO2 FOREIGN KEY(USER_NO) REFERENCES USER_INFO(USER_NO)
		ON DELETE CASCADE
);




CREATE SEQUENCE GAME_NOSQ NOCACHE;

CREATE TABLE GAME(
	GAME_NO NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(500) NOT NULL,
	GAME_REGION VARCHAR2(100) NOT NULL,
	GAME_STADIUM VARCHAR2(500) NOT NULL,
	GAME_ADDR VARCHAR2(500) NOT NULL,
	GAME_DATE DATE NOT NULL,
	GAME_TIME VARCHAR2(100) NOT NULL,
	GAME_PEOPLE NUMBER NOT NULL,
	GAME_MERCENARY NUMBER DEFAULT 0,
	GAME_CONTENT VARCHAR2(4000),
	GAME_TYPE VARCHAR2(2) DEFAULT 'N' CHECK(GAME_TYPE IN('N','Y') ),
	CONSTRAINT FK_USER_ID3 FOREIGN KEY(USER_ID) REFERENCES USER_INFO(USER_ID)
		ON DELETE CASCADE
);




CREATE SEQUENCE ASK_NOSQ NOCACHE;
CREATE SEQUENCE ASK_GPNOSQ NOCACHE;
CREATE SEQUENCE ASK_GPSQ NOCACHE;

CREATE TABLE GAME_ASK(
	ASK_NO NUMBER PRIMARY KEY,
	GAME_NO NUMBER NOT NULL,
	ASK_TYPE VARCHAR2(100) NOT NULL,
	ASK_GPNO NUMBER NOT NULL,
	ASK_GPSQ NUMBER NOT NULL,
	USER_ID VARCHAR2(500) NOT NULL,
	ASK_CONTENT VARCHAR2(4000),
	ASK_REG DATE NOT NULL,
	ASK_STATUS VARCHAR2(2) DEFAULT 'N' CHECK(ASK_STATUS IN('N','Y') ),
	CONSTRAINT FK_USER_ID4 FOREIGN KEY(USER_ID) REFERENCES USER_INFO(USER_ID)
		ON DELETE CASCADE,
	CONSTRAINT FK_GAME_NO1 FOREIGN KEY(GAME_NO) REFERENCES GAME(GAME_NO)
		ON DELETE CASCADE	
);



CREATE TABLE GAME_PIC(
	GAME_NO NUMBER NOT NULL,
	PIC_NAME VARCHAR2(500) NOT NULL,
	PIC_PATH VARCHAR2(1000) NOT NULL,
	CONSTRAINT FK_GAME_NO2 FOREIGN KEY(GAME_NO) REFERENCES GAME(GAME_NO)
		ON DELETE CASCADE
);



CREATE SEQUENCE QNA_NOSQ NOCACHE;
CREATE SEQUENCE QNA_GPNOSQ NOCACHE;
CREATE SEQUENCE QNA_GPSQ NOCACHE;

CREATE TABLE QNA(
	QNA_NO NUMBER PRIMARY KEY,
	QNA_GPNO NUMBER NOT NULL,
	QNA_GPSQ NUMBER NOT NULL,
	QNA_TITLE VARCHAR2(2000) NOT NULL,
	QNA_CONTENT VARCHAR2(4000) NOT NULL,
	USER_ID VARCHAR2(500) NOT NULL,
	QNA_REG DATE NOT NULL,
	QNA_TYPE VARCHAR2(100) NOT NULL,
	CONSTRAINT FK_USER_ID5 FOREIGN KEY(USER_ID) REFERENCES USER_INFO(USER_ID)
		ON DELETE CASCADE
);



CREATE SEQUENCE FAQ_NOSQ NOCACHE;
CREATE SEQUENCE FAQ_GPNOSQ NOCACHE;
CREATE SEQUENCE FAQ_GPSQ NOCACHE;

CREATE TABLE FAQ(
	FAQ_NO NUMBER PRIMARY KEY,
	FAQ_GPNO NUMBER NOT NULL,
	FAQ_GPSQ NUMBER NOT NULL,
	FAQ_TITLE VARCHAR2(2000) NOT NULL,
	FAQ_CONTENT VARCHAR2(4000) NOT NULL,
	USER_ID VARCHAR2(500) NOT NULL,
	FAQ_REG DATE NOT NULL,
	FAQ_TYPE VARCHAR2(100) NOT NULL,
	CONSTRAINT FK_USER_ID6 FOREIGN KEY(USER_ID) REFERENCES USER_INFO(USER_ID)
		ON DELETE CASCADE
);

CREATE TABLE GAME_APPLY(
	GAME_NO NUMBER NOT NULL,
	USER_NO NUMBER NOT NULL,
	CONSTRAINT FK_GAME_NO3 FOREIGN KEY(GAME_NO) REFERENCES GAME(GAME_NO)
		ON DELETE CASCADE,
	CONSTRAINT FK_USER_NO3 FOREIGN KEY(USER_NO) REFERENCES USER_INFO(USER_NO)
		ON DELETE CASCADE
);

DROP TABLE GAME_APPLY;

DROP TABLE FAQ;
DROP SEQUENCE FAQ_NOSQ;
DROP SEQUENCE FAQ_GPNOSQ;
DROP SEQUENCE FAQ_GPSQ;

DROP TABLE QNA;
DROP SEQUENCE QNA_NOSQ;
DROP SEQUENCE QNA_GPNOSQ;
DROP SEQUENCE QNA_GPSQ;

DROP TABLE GAME_PIC;

DROP TABLE GAME_ASK;
DROP SEQUENCE ASK_NOSQ;
DROP SEQUENCE ASK_GPNOSQ;
DROP SEQUENCE ASK_GPSQ;

DROP TABLE GAME;
DROP SEQUENCE GAME_NOSQ;

DROP TABLE MERCENARY_INFO;

DROP TABLE TEAM_ASK;
DROP SEQUENCE TMASK_NOSQ;
DROP SEQUENCE TMASK_GPNOSQ;
DROP SEQUENCE TMASK_GPSQ;

DROP TABLE TEAM_PIC;
DROP SEQUENCE TEAM_PIC_NOSQ;

DROP TABLE TEAM_INFO;
DROP SEQUENCE TEAM_NOSQ;

DROP TABLE REVIEW;
DROP SEQUENCE REVIEW_NOSQ;

DROP TABLE STADIUM_PIC;

DROP TABLE STADIUM;
DROP SEQUENCE STADIUM_NOSQ;

DROP TABLE USER_INFO;
DROP SEQUENCE USER_NOSQ;


SELECT * FROM USER_INFO;

SELECT * FROM TEAM_INFO;

SELECT * FROM TEAM_PIC;

SELECT * FROM MERCENARY_INFO;

SELECT t.TEAM_NO, t.USER_NO, p.PIC_PATH, t.TEAM_NAME, t.TEAM_INTRO, t.TEAM_ADDCHK
		FROM TEAM_INFO t 
		LEFT JOIN TEAM_PIC p ON t.TEAM_NO = p.TEAM_NO
		ORDER BY TEAM_NO DESC




















