DROP TABLE USER_INFO;
DROP SEQUENCE USER_NOSQ;

CREATE SEQUENCE USER_NOSQ NOCACHE;

CREATE TABLE USER_INFO(
	USER_NO NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(500) UNIQUE,
	USER_PW VARCHAR2(500) NOT NULL,
	USER_NAME VARCHAR2(500) NOT NULL,
	USER_GENDER VARCHAR2(2) CHECK(USER_GENDER IN('F','M') ),
	USER_BIRTHDATE VARCHAR2(500) NOT NULL,
	USER_EMAIL VARCHAR2(200) UNIQUE,
	USER_PHONE VARCHAR2(20) NOT NULL,
	USER_ZIP VARCHAR2(20) NOT NULL,
	USER_ADDR VARCHAR2(1000),
	USER_ROLE VARCHAR2(50) NOT NULL
);

DROP TABLE STADIUM;
DROP SEQUENCE STADIUM_NOSQ;

CREATE SEQUENCE STADIUM_NOSQ NOCACHE;

CREATE TABLE STADIUM(
	STADIUM_NO NUMBER PRIMARY KEY,
	STADIUM_NAME VARCHAR2(500) NOT NULL,
	STADIUM_ADDR VARCHAR2(1000) NOT NULL,
	STADIUM_CONTENT VARCHAR2(4000) NOT NULL
);

DROP TABLE REVIEW
DROP SEQUENCE REVIEW






















